import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar/Navbar";
import FooterUI from "@/components/layouts/Footer/FooterUI";
import Whatsapp from "@/components/partials/Whatsapp/Whatsapp";
import FlyButton from "@/components/partials/FlyButton/FlyButton";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Perintis Timbangan Indonesia",
  description: "Generated by create next app",
  icons: {
    icon: "/svg/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Script
        id="gtm"
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PN8TGQN7');`,
        }}
      />
      <html lang="en">
        <body>
          <noscript
            dangerouslySetInnerHTML={{
              __html: `<iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PN8TGQN7"
height="0" width="0" style="display:none;visibility:hidden"></iframe>`,
            }}
          ></noscript>
          <Navbar />
          {/* <Whatsapp /> */}
          <FlyButton />
          <main className="flex flex-col min-h-screen overflow-x-hidden">
            {children}
          </main>
          <FooterUI />
        </body>
      </html>
    </>
  );
}
